In [1]:
# Creating matrices
A <- matrix(c(3, 2, 9, 5), nrow = 2, byrow = TRUE)
B <- matrix(c(7, 1, 6, 4), nrow = 2)
C <- rbind(c(1, 2, 3), c(6, 5, 4))
D <- cbind(c(9, 5, 1), c(3, 2, 7))

In [2]:
# Display matrices
print("Matrix A"); print(A)
print("Matrix B"); print(B)
print("Matrix C"); print(C)
print("Matrix D"); print(D)

[1] "Matrix A"
     [,1] [,2]
[1,]    3    2
[2,]    9    5
[1] "Matrix B"
     [,1] [,2]
[1,]    7    6
[2,]    1    4
[1] "Matrix C"
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    6    5    4
[1] "Matrix D"
     [,1] [,2]
[1,]    9    3
[2,]    5    2
[3,]    1    7


In [3]:
# Matrix operations
print("Addition A + B"); print(A + B)
print("Subtraction A - B"); print(A - B)
print("Scalar Multiplication 3 * A"); print(3 * A)
print("C %*% D"); print(C %*% D)
print("Diagonal of A"); print(diag(A))
print("Transpose of C"); print(t(C))
print("Inverse of B"); print(solve(B))

[1] "Addition A + B"
     [,1] [,2]
[1,]   10    8
[2,]   10    9
[1] "Subtraction A - B"
     [,1] [,2]
[1,]   -4   -4
[2,]    8    1
[1] "Scalar Multiplication 3 * A"
     [,1] [,2]
[1,]    9    6
[2,]   27   15
[1] "C %*% D"
     [,1] [,2]
[1,]   22   28
[2,]   83   56
[1] "Diagonal of A"
[1] 3 5
[1] "Transpose of C"
     [,1] [,2]
[1,]    1    6
[2,]    2    5
[3,]    3    4
[1] "Inverse of B"
            [,1]       [,2]
[1,]  0.18181818 -0.2727273
[2,] -0.04545455  0.3181818
